[QUAD-196]: Added the ability to view all the public networks in quadriga.
diging/quadriga pull request #328
Opened 2016-09-24 00:43 UTC by suprajkolluri

[QUAD-196]: Added the ability to view all the public networks in quadriga in a single page in quadriga/sites section.

2016-09-24 00:43 UTC, suprajkolluri commented
@jdamerow Please review. Also I have squashed my commits to make the commit history look clean :)

2016-09-26 22:09 UTC, jdamerow commented on Quadriga/src/main/java/edu/asu/spring/quadriga/service/network/impl/NetworkManager.java
> +            logger.error("Something went wrong in DB", e);
the method signature says it throws an exception but here you just log it and don't throw anything.

2016-09-26 22:16 UTC, jdamerow commented on Quadriga/src/main/java/edu/asu/spring/quadriga/rest/open/NodeInfoController.java
> +                    || occur.getProject().getUnixName().equals("unkown")) {
where is this coming from? why is this checking for a project with unix name "unkown" (which is misspelled btw).

2016-09-26 22:17 UTC, jdamerow commented on Quadriga/src/main/java/edu/asu/spring/quadriga/service/network/impl/NetworkTransformationManager.java
> +        ITransformedNetwork networkJSon = null;
declare where it's actually needed

2016-09-26 22:18 UTC, jdamerow commented on Quadriga/src/main/java/edu/asu/spring/quadriga/service/network/impl/NetworkTransformationManager.java
> +                return null;
same thing here: method declares an exception but non is thrown.

2016-09-26 22:18 UTC, jdamerow commented on Quadriga/src/main/java/edu/asu/spring/quadriga/service/network/impl/NetworkTransformationManager.java
> +        networkJSon = transformer.transformNetwork(networkTopNodesList);
just return directly in this line

2016-09-26 22:19 UTC, jdamerow commented on Quadriga/src/main/java/edu/asu/spring/quadriga/service/network/mapper/impl/NetworkMapper.java
> +            networkList = getNetworkListFromDTOList(networksDTO);
return here

2016-09-26 22:20 UTC, jdamerow requested changes

2016-09-27 15:59 UTC, suprajkolluri commented on Quadriga/src/main/java/edu/asu/spring/quadriga/rest/open/NodeInfoController.java
> +                    || occur.getProject().getUnixName().equals("unkown")) {
This is coming from the UI, views/public/sites/publicnetworks.jsp line 147.
Corrected the spelling in the jsp also

2016-09-27 16:21 UTC, closed without merging