[QUAD-196]: Added the ability to view all the public networks in quadriga.
diging/quadriga pull request #330
Opened 2016-09-28 21:25 UTC by suprajkolluri

Added the ability to view all the public networks in quadriga in a single page in quadriga/sites section.

2016-09-28 21:45 UTC, jdamerow commented
ok to test

2016-09-28 21:49 UTC, jdamerow commented
There should be no whitespace on the right on this page:
![image](https://cloud.githubusercontent.com/assets/8881141/18933687/ca867c62-858a-11e6-8d43-2b715e5458d5.png)

2016-09-28 21:52 UTC, jdamerow commented
Menu entries:
- Home should be "All Projects"
- Public networks should be "Explore the Graph"

2016-09-28 21:53 UTC, jdamerow commented
And since you're on it, would you please add a little loading icon in the concept description box and text occurrences box while the content for those is being retrieved? Otherwise, looks great!

2016-09-28 21:53 UTC, jdamerow requested changes

2016-09-28 21:53 UTC, jdamerow commented on Quadriga/src/main/java/edu/asu/spring/quadriga/dao/impl/NetworkDAO.java
> +            logger.error("Error in fetching a network status: ", e);
remove logger. exception will be logged when handled. And does the ```list``` method really throw just ```Exception```?

2016-09-28 21:53 UTC, jdamerow commented on Quadriga/src/main/java/edu/asu/spring/quadriga/rest/open/NodeInfoController.java
> +            if (occur.getProject().getUnixName().equals(projectUnix.trim()) || "".equals(projectUnix.trim())) {
why not use the ```isEmpty``` method?

2016-09-28 21:53 UTC, jdamerow commented on Quadriga/src/main/java/edu/asu/spring/quadriga/rest/open/NodeInfoController.java
> +                if (flag) {
why do you set a flag? Why not do the condition check right here? Also, that only text occurrences of public projects should be returned, is always true. So you can always check for that, not just when there is no unix name.

2016-09-28 21:53 UTC, jdamerow commented on Quadriga/src/main/webapp/WEB-INF/tiles/layouts/skeleton_public_sites.jsp
> +		</div>
please fix indentation

2016-09-28 21:53 UTC, jdamerow commented on Quadriga/src/main/webapp/WEB-INF/tiles/layouts/skeleton_public_sites.jsp
> +			</div>
here too

2016-09-28 21:53 UTC, jdamerow commented on Quadriga/src/main/webapp/WEB-INF/views/public/sites/nav-networkrightplane.jsp
> +</c:if>
don't indent html that much please

2016-09-28 21:54 UTC, closed without merging

2016-09-30 20:56 UTC, suprajkolluri commented on Quadriga/src/main/java/edu/asu/spring/quadriga/dao/impl/NetworkDAO.java
> +            logger.error("Error in fetching a network status: ", e);
It throws HibernateException, do you want to me to wrap it in QuadrigaStorage exception leave it for the calling method to handle?

2016-09-30 21:11 UTC, suprajkolluri commented on Quadriga/src/main/webapp/WEB-INF/tiles/layouts/skeleton_public_sites.jsp
> +			</div>
I am using the IDE XML formatter, do we have any format template for XMLs?

2016-09-30 21:14 UTC, jdamerow commented on Quadriga/src/main/java/edu/asu/spring/quadriga/dao/impl/NetworkDAO.java
> +            logger.error("Error in fetching a network status: ", e);
yes, and always catch specific exceptions, never just exception.

2016-09-30 21:17 UTC, suprajkolluri commented on Quadriga/src/main/webapp/WEB-INF/views/public/sites/nav-networkrightplane.jsp
> +</c:if>
For indentation I am using the IDE XML Formatting, do we have a template/specification for XMLs too?