Story/quad 226
diging/quadriga pull request #331
Opened 2016-09-30 21:59 UTC by snilapwa

2016-10-03 15:41 UTC, jdamerow requested changes

2016-10-03 15:41 UTC, jdamerow commented on Quadriga/src/main/webapp/WEB-INF/views/workspace/workspacedetails.jsp
> +                            textFileAccessMap["PRIVATE"] = "Are you sure you want to make this text file Public";
Question marks are missing for both questions.

2016-10-05 15:38 UTC, snilapwa commented
Corrected file access change confirmation message, please help to review

2016-10-05 16:29 UTC, jdamerow commented on Quadriga/src/main/webapp/WEB-INF/views/workspace/workspacedetails.jsp
> +                            textFileAccessMap["PRIVATE"] = "Are you sure you want to make this text file Public ?";
There is no blank before a period, question mark, or exclamation mark in a sentence.

2016-10-05 16:47 UTC, snilapwa commented
Corrected message.

2016-10-05 17:05 UTC, jdamerow commented
ok to test

2016-10-05 17:21 UTC, jdamerow approved these changes

2016-10-05 17:21 UTC, merged