Story/quad 216
diging/quadriga pull request #336
Opened 2016-10-07 20:42 UTC by snilapwa

2016-10-11 20:35 UTC, jdamerow commented
ok to test

2016-10-11 20:44 UTC, jdamerow commented
the layout of the sites page is off:
![image](https://cloud.githubusercontent.com/assets/8881141/19287966/d1a15962-8fb8-11e6-8407-aab54fb3401b.png)

2016-10-11 20:46 UTC, jdamerow commented
footer is missing on network visualization pages (network and explore):
![image](https://cloud.githubusercontent.com/assets/8881141/19288042/1e98a3a6-8fb9-11e6-9528-3cfc414d9421.png)

2016-10-12 22:56 UTC, jdamerow requested changes

2016-10-12 22:56 UTC, jdamerow commented on Quadriga/src/main/webapp/resources/public/css/footer.css
> +#c {
where is 'c' used? not a good name.

2016-10-12 22:59 UTC, jdamerow commented
Otherwise good. Once the last thing is fixed, it's ready to merge!

2016-10-13 19:19 UTC, snilapwa commented
'c' function is for copyright footer, it is used in most of the skeleton pages and is defined in main.css.
I have changed its name to copyrightwrap in footer.css for my changes

2016-10-13 20:41 UTC, jdamerow approved these changes

2016-10-13 20:41 UTC, merged

2016-10-13 20:42 UTC, jdamerow commented
@snilapwa for the next branch please make sure to lowercase 'Story': story/QUAD-1 instead of Story/QUAD-1