[QUAD-235] Fixing the current error and also adding csrf headers
diging/quadriga pull request #338
Opened 2016-10-18 18:48 UTC by suprajkolluri

Fixing the current error and also adding csrf headers to all ajax post calls

2016-10-22 10:33 UTC, jdamerow commented on Quadriga/src/main/webapp/WEB-INF/tiles/layouts/skeleton_right.jsp
> +    <meta name="_csrf_header" content="${_csrf.headerName}"/>
why do you put the csrf token here?

2016-10-22 10:33 UTC, jdamerow commented on Quadriga/src/main/webapp/WEB-INF/views/conceptcollections/collectiondetails.jsp
> +									var token = $("meta[name='_csrf']").attr("content");
why do you go through metatags and not put the EL expression right hear?

2016-10-26 21:38 UTC, suprajkolluri commented
@jdamerow removed meta tags and directly used el to access csrf tokens, Please review

2016-10-27 07:51 UTC, jdamerow commented
ok to test

2016-10-27 07:59 UTC, jdamerow requested changes

2016-10-27 07:59 UTC, jdamerow commented on Quadriga/src/main/webapp/resources/txt-layout/js/d3networkvisualize.js
> +    var header = '${_csrf.headerName}';
these will not be replace. They are static files that are not run through the jsp engine.

2016-10-27 07:59 UTC, jdamerow commented on Quadriga/src/main/webapp/resources/txt-layout/js/editnetworks.js
> +	var header = '${_csrf.headerName}';
same here

2016-10-27 07:59 UTC, jdamerow commented on Quadriga/src/main/webapp/resources/js/handleResult.js
> +    var header = '${_csrf.headerName}';
static file

2016-11-04 17:50 UTC, jdamerow approved these changes

2016-11-04 17:52 UTC, merged