[QUAD-236] : Validate input XML and return correct error message
diging/quadriga pull request #345
Opened 2016-10-26 18:45 UTC by snilapwa

2016-11-01 17:25 UTC, jdamerow requested changes

2016-11-01 17:25 UTC, jdamerow commented on Quadriga/src/main/java/edu/asu/spring/quadriga/service/passthroughproject/impl/XMLReader.java
> +            throw new DocumentParserException(e.getMessage());
don't swallow the stacktrace

2016-11-01 17:25 UTC, jdamerow commented on Quadriga/src/main/java/edu/asu/spring/quadriga/service/passthroughproject/impl/XMLReader.java
> +            throw new DocumentParserException("Please provide a " + tagName + " id as a part of the XML");
Should be "Please provide an id attribute for tag: tagname".

2016-11-01 17:25 UTC, jdamerow commented on Quadriga/src/main/java/edu/asu/spring/quadriga/service/passthroughproject/impl/XMLReader.java
> +            throw new DocumentParserException("Please provide a " + tagName + " id as a part of the XML");
And actually, I don't think this is correct. Please check the logic, but I think a user can create a project or workspace by submitting no ids.

2016-11-02 18:44 UTC, snilapwa commented on Quadriga/src/main/java/edu/asu/spring/quadriga/service/passthroughproject/impl/XMLReader.java
> +            throw new DocumentParserException("Please provide a " + tagName + " id as a part of the XML");
Yes, User can upload without providing project id and/or workspace id. In that case user should not include project/workspace tag in input XML. But, if user add tag 'project' and/or 'workspace' and do not provide id for the tag, we get null pointer exception.

2016-11-02 19:06 UTC, jdamerow approved these changes

2016-11-02 19:06 UTC, jdamerow commented
ok to test

2016-11-02 19:08 UTC, jdamerow commented on Quadriga/src/main/java/edu/asu/spring/quadriga/service/passthroughproject/impl/XMLReader.java
> +        }
Generally using exceptions to validate input is not good practice. But for now let's leave it like that.

2016-11-02 19:11 UTC, merged