Story/quad 230
diging/quadriga pull request #367
Opened 2017-04-10 19:22 UTC by susmitha8

In the Networks page of Quadriga, the functionality of displaying the modal window with text on click of the title, author and creation date with the clicked node being highlighted is implemented. The handle is displayed as link when shown(i.e., if the text doesn't have title,author and creation date).

2017-04-10 19:31 UTC, jdamerow requested changes

2017-04-10 19:31 UTC, jdamerow commented on Quadriga/src/main/java/edu/asu/spring/quadriga/rest/open/NodeInfoController.java
> +    public ResponseEntity<String> getTextsForConcepts(@RequestParam String conceptId, @RequestParam String projectUnix, Model model)
no model needed here. remove.

2017-04-10 19:31 UTC, jdamerow commented on Quadriga/src/main/java/edu/asu/spring/quadriga/rest/open/NodeInfoController.java
> +        //model.addAttribute()
remove

2017-04-10 19:31 UTC, jdamerow commented on Quadriga/src/main/java/edu/asu/spring/quadriga/rest/open/NodeInfoController.java
> +                    occurance.append("textCreationDate", occur.getCreationDate());
code duplication, let's extract that into a method.

2017-04-10 19:31 UTC, jdamerow commented on Quadriga/src/main/java/edu/asu/spring/quadriga/service/network/domain/impl/TextOccurance.java
> +    }
getters and setter need to come after the other getter and setters

2017-04-10 19:31 UTC, jdamerow commented on Quadriga/src/main/webapp/WEB-INF/views/public/nav/nav-networkrightplane.jsp
> +<script src="${pageContext.servletContext.contextPath}/resources/js/cytoscape/publicNetwork.js" ></script>
this should already be included in the main jsp, so this would just load it twice. remove.

2017-04-10 19:31 UTC, jdamerow commented on Quadriga/src/main/webapp/resources/js/cytoscape/publicNetwork.js
> +		getEntireText(node,path);
why is this being called here?

2017-04-10 19:31 UTC, jdamerow commented on Quadriga/src/main/webapp/resources/js/cytoscape/publicNetwork.js
> +}
needs proper indentation

2017-04-10 19:31 UTC, closed without merging

2017-04-13 19:00 UTC, susmitha8 commented on Quadriga/src/main/webapp/resources/js/cytoscape/publicNetwork.js
> +		getEntireText(node,path);
Because on click of the node, the getEntireText function needs to be called to get the entire text. Isn't this right?

2017-04-17 15:10 UTC, susmitha8 commented on Quadriga/src/main/java/edu/asu/spring/quadriga/rest/open/NodeInfoController.java
> +    public ResponseEntity<String> getTextsForConcepts(@RequestParam String conceptId, @RequestParam String projectUnix, Model model)
removed the model

2017-04-17 15:13 UTC, susmitha8 commented on Quadriga/src/main/java/edu/asu/spring/quadriga/rest/open/NodeInfoController.java
> +                    occurance.append("textCreationDate", occur.getCreationDate());
extracted into a method "appendCall"

2017-04-17 15:13 UTC, susmitha8 commented on Quadriga/src/main/java/edu/asu/spring/quadriga/rest/open/NodeInfoController.java
> +        //model.addAttribute()
removed

2017-04-17 15:18 UTC, susmitha8 commented on Quadriga/src/main/java/edu/asu/spring/quadriga/service/network/domain/impl/TextOccurance.java
> +    }
changed the place of getters and setters for the author, title and creation date(i.e., written after the other getters and setters)

2017-04-17 15:26 UTC, susmitha8 commented on Quadriga/src/main/webapp/WEB-INF/views/public/nav/nav-networkrightplane.jsp
> +<script src="${pageContext.servletContext.contextPath}/resources/js/cytoscape/publicNetwork.js" ></script>
Yes, it is already included in the main jsp. Removed the script from nav-networkrightplane.jsp.

2017-04-17 15:28 UTC, susmitha8 commented on Quadriga/src/main/webapp/resources/js/cytoscape/publicNetwork.js
> +}
Okay. Indented properly.