[QUAD-260] Removed JAXB annotations from DTOs.
diging/quadriga pull request #393
Opened 2017-10-23 19:01 UTC by chiraag-subramanian

2017-10-27 22:16 UTC, abhikrish503501 approved these changes
The annotations have been removed properly and indentation is good

2017-10-27 22:18 UTC, Mihika0409 approved these changes

2017-10-27 23:24 UTC, jdamerow commented
ok to test

2017-10-27 23:30 UTC, jdamerow requested changes
make sure you don't break the code; eclipse should have been all over with compiler errors;

2017-10-27 23:30 UTC, jdamerow commented on Quadriga/src/main/java/edu/asu/spring/quadriga/dto/WorkspaceDTO.java
> -import javax.xml.bind.annotation.XmlTransient;
don't delete just the imports; you also need to delete where they are used. eclipse should have given you an error if you do that.

2017-10-31 16:36 UTC, abhikrish503501 approved these changes
Removed the annotations

2017-10-31 16:46 UTC, jdamerow approved these changes

2017-10-31 16:46 UTC, merged